#defining function
def function(input):
    #creating dictionary with letters corresponding to each triplets
    #RNA codon table given by rosalind
    codons = {
        'F': ['UUU', 'UUC'],
        'L': ['UUA', 'UUG', 'CUU', 'CUC', 'CUA', 'CUG'],
        'S': ['UCU', 'UCC', 'UCA', 'UCG', 'AGU', 'AGC'],
        'Y': ['UAU', 'UAC'],
        'C': ['UGU', 'UGC'],
        'W': ['UGG'],
        'P': ['CCU', 'CCC', 'CCA', 'CCG'],
        'H': ['CAU', 'CAC'],
        'Q': ['CAA', 'CAG'],
        'R': ['CGU', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG'],
        'V': ['GUU', 'GUC', 'GUA', 'GUG'],
        'A': ['GCU', 'GCC', 'GCA', 'GCG'],
        'D': ['GAU', 'GAC'],
        'E': ['GAA', 'GAG'],
        'G': ['GGU', 'GGC', 'GGA', 'GGG'],
        'I': ['AUU', 'AUC', 'AUA'],
        'M': ['AUG'],
        'T': ['ACU', 'ACC', 'ACA', 'ACG'],
        'N': ['AAU', 'AAC'],
        'K': ['AAA', 'AAG'],
        #stop codon
        '*': ['UAA', 'UAG', 'UGA'],
        }

    number = 1
    for x in input:
        number = (number * len(codons[x]))
    #stop codon 
    number = (number*len(codons["*"]))
    #returning 
    return number % 1000000

#taking input and returning result 
a = 'MPKASLRKAEDGLERDTYFWFRQRCKGGLWASEPFEQKRDQFAVAYLSIWSQRNSCQHGFIGEIHVWVQICIHYINFKYCAPEYLWPVGPAHICPMLEVLVTQYFDYQFLLWKMDLGRIDVLPSWQFKFPLLRTEYYVMHEMEGIIHWAIEHEICGLTRTEEFLFVWITECICHQSRKYDVATLQQEECMSTMAPNPMNAHSLATHMSDTYMDVHGLKTAAWMWLCPYNRTPHTRLEQPHDHFSVFTFWKMPGNANYLIPTCDARQISTWEQFAILVRLWKWMMDYNNNGDSVLRVFEKKEWNVTTLCYPICWWCMYRWQAIKITLRGWILSCKFIIPYIKCTHIELTALVNPGKMFKLIVICWLGRRIDNAGHHRGILRMPFAGVIPNWQNFRLMVSDNEDSLYPSKGQPPNRMPRPKVKQCMELVCAMDNSYRAVHSPWVLPRSAVLRAPSMGMANIKDSITVIHVSNDPYEPWWPNWKPKFMRSKLVGVPHRIMASWRLNFVIYIEYGEMYYKETEFSMKAWMLQKQYLNNKICLSQYEGAHNERYFMSCRDYGNTAEQPYADGLAYFWYPQEIHAMMWVNGDCSGNTEEWEMGWTYSWPEFPEINFFWAMVYEFFYWDKPVETLINTRYSKCNPDWNKIDKYPAKTRQVEVVMGSDSRQVIDDRVIFGPMSVRQFRPRTGLWMQIGAIHIVPHHFMHEHPPMKTAVCQILNPGWFICGEIHLASTEAHGTTLWNHVVMSCCRYETISTNYSAGAQWGTLRWWVFKWHTCWAQQVVPANESPTVYRWKWERQCHKCSVVHTCHMHRQRLCDKFPFTQHGCHRWHMKMRHSTETPLLLVPTLPIGYENNFEGPRVIWSDAEFYWIYGKGGDIVTELCGNHQTPDEYHPPYSGDIASRWKFCQCWIQYFCFWLCSNTHNPCKREIKCDRPFWAYGFCKGSMRRIWCSQVHVVLVNEVAWFPYHEKWQKTYCYETQQQAAYSICEQRSDYLMYIAGWWCE'
print(function(a))